image: python:3.9-slim

stages:
  - test
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml

heroku:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - apt update
    - apt install ruby-dev -y
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - master
  environment:
    name: heroku
    url: $ENV_URL
